### ISSUE TITLE
Reactify blogthedata.com

### ISSUE THREAD

**Issue by jsolly** [jsolly/blogthedata#20]
#### Context 
One goal of this site is to teach me web development frameworks. Now it's entirely possible to write the whole app without a single line of JavaScript, but that's silly if I want to get into the Web Dev world.

Thus, a big step for blogthedata.com is to separate the front and backend. There are plenty of tutorials online about 'reactifying' a Django app. 

#### Ideal behavior
I imagine a React.js app that controls what we show to the user. When the app needs to interact with a Database, it should make REST calls to Django which handles the request, makes any needed db changes, and then responds with what React needs.

#### Things to consider
There will need to be a lot of architecture changes. We should finish the [architecture diagram](https://github.com/jsolly/blogthedata/issues/18) before taking on this issue.
Might want to pick up [this book](https://www.amazon.com/Decoupled-Django-Valentino-Gagliardi/dp/1484271432/ref=sr_1_1?crid=78531N8EUKP3&keywords=django+javascript&qid=1652119538&sprefix=django+javascript%2Caps%2C135&sr=8-1).

**Comment by justin107d** [comment]
You mentioned htmx in another issue which, from what I understand, some in the django community are excited about because it gets them away from working with javascript frameworks.  I'm not sure if these work well together so you may want to research how you use each of these and where they go.

**Comment by jsolly** [comment]
I think @justin107d is right. I've done some digging into both the React and HTMX routes and I believe HTMX is the best path forward because:
1 - I don't feel confident in the various JS front-end frameworks. It would be pretty difficult to split an app in half at the same time I learn new frameworks.
2 - There would be a performance hit as all requests for data would need to be passed via HTTP. 

I am going to close this issue and keep going the 'Django Way'

I'll create a separate project for learning all the JS stuff.
