### ISSUE TITLE
Error installing virtual environment with venv

### ISSUE THREAD

**Issue by freedompraise** [jsolly/blogthedata#252]
I am attempting to install this project on my linux machine by following the installation commands provided in the README file. However, I have encountered an error when trying to install the virtual environment using venv. Specifically, when running the command:

$ python3 -m venv blogthedata/django_project/venv

I receive the following error message:

bash: blogthedata/django_project/venv/bin/activate: No such file or directory

**Comment by jsolly** [comment]
Hey! Thanks for the issue.

That command creates a virtual environment, so you just need to make sure you are in the right directory when you run the command.

If you are in the root directory, the subdirectories should look like this:
blogthedata
├── LICENSE
├── README.md
├── backups
├── config
├── coverage
├── django_project
│   ├── venv
├── docs
├── media
└── utilities

Make sure you are one level higher than `django_project` when running that command.

**Comment by freedompraise** [comment]
Alright, let me try it out and give feesback

**Comment by freedompraise** [comment]
it worked, thanks
