### ISSUE TITLE
Error connecting to Postgresql server on socket "/var/run/postgresql/.s.PGSQL.5432"

### ISSUE THREAD

**Issue by freedompraise** [jsolly/blogthedata#253]
When attempting to run the PostgreSQL server and connect to it using the `sudo -u postgres psql`
 command, I encounter the following error message:
`psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
Is the server running locally and accepting connections on that socket?
`

I am following the setup instructions provided in the README of the project, and the instructions do not mention starting the database service before attempting to open the PostgreSQL terminal.

**Comment by jsolly** [comment]
What Operating system are you on?

I suggested using the [postgres app](https://github.com/PostgresApp/PostgresApp).

Are you able to connect to the postgres Database using another tool like [Pgadmin](https://www.pgadmin.org/)?

You'll want to make sure postgres is installed. What happens when you type
```shell
$ postgres --version
```

**Comment by freedompraise** [comment]
I'm using an Ubuntu OS

The issue resulted because the postgresql server was not running. 
After installing posgresql, you have to manually start the server using `sudo service postgreSQL start`. 
That should come before running `sudo -u postgres psql`

**Comment by jsolly** [comment]
Great! I will add this as a note!

**Comment by jsolly** [comment]
https://github.com/jsolly/blogthedata/commit/dcb1fd64840fe55b649745773c39c5735eaa2de8
