### ISSUE TITLE
Error creating tables on database

### ISSUE THREAD

**Issue by freedompraise** [jsolly/blogthedata#255]
**Description**
 When running `python manage.py migrate`, a _psycopg2.errors.UndefinedTable_ error is raised, stating that "relation 'blog_category' does not exist". The traceback shows that the error is caused by the absence of the 'blog_category' table in the database.

Those are the last two lines of the error message. I could add the entire error message if need be for context.

**Steps To Reproduce**
1. Go to 'blogthedata/django_project'
2. On cli, run `python manage.py migrate`, or basically any command that includes `python manage.py`

**Expected Result**
The migrations run successfully and the necessary tables are created in the database.

**Actual result** 
The psycopg2.errors.UndefinedTable error is raised, stating that "relation 'blog_category' does not exist".

**Additional Information**
I am using the requirements installed from the project's requirements file, using python 3.10 on a Linux System

**Comment by jsolly** [comment]
This is an issue that does have a workaround, but I wish the workflow could be improved.

If you are migrating for the first time on an empty db, you need to go into [this file](https://github.com/jsolly/blogthedata/blob/master/django_project/blog/forms.py#L14) and uncomment these lines
```py
if settings.SETTINGS_MODULE in [
    "django_project.settings.dev",
    "django_project.settings.prod",
]:
    choices = Category.objects.all().values_list("name", "name")
```

Once the migration is complete, you can put the code back to the way it was.

I haven't been able to figure out how to fix this issue without this hack. 

Luckily it's just for the initial migration.

**Comment by jsolly** [comment]
Hey @freedompraise, did that work for you?

**Comment by freedompraise** [comment]
Yes, it worked. Although, I had to comment a few lines of code in the settings file as well
