### ISSUE TITLE
Error in accessing post detail page due to missing reverse URL for category

### ISSUE THREAD

**Issue by freedompraise** [jsolly/blogthedata#292]
**Description:**
When accessing a post detail page on the website, an error occurs indicating a missing reverse URL for the category. This error prevents users from viewing the post and disrupts the expected navigation flow.

**Steps to reproduce:**
- Create a category in the admin site and assign it a slug of "webdev".
- Create a post with a slug of "elite_class_app".
- Navigate to the home page where all posts are listed.
- Click on the post with the slug "elite_class_app" to open it.

**Expected behavior:**
The post detail page should open successfully, displaying the content of the post and any associated information.

**Actual behavior:**
Upon clicking the post, an error page is displayed with the following message:

```js
NoReverseMatch at /post/elite_class_app/
Reverse for 'blog-category' with arguments '('Web Dev',)' not found. 1 pattern(s) tried: ['category/(?P<slug>[-a-zA-Z0-9_]+)/\\Z']
```

**Additional information:**
This error seems to be related to the reverse URL lookup for the category. The error message suggests that the reverse URL for the "blog-category" view with the argument "Web Dev" is not found. This issue prevents the post detail page from being accessed.

**Proposed solution:**
- Investigate the existing URL configuration and ensure that the URL pattern for the "blog-category" view is correctly defined.
- Verify that the slug used for the category matches the one specified in the URL pattern.
- Check the corresponding view and template to confirm that the category information is correctly passed and rendered on the post detail page.

**Comment by freedompraise** [comment]
Alright

> The issue might be that there is a space in the category name. I can look into this one.
Okay. Let me know what you come up with

**Comment by jsolly** [comment]
I tried to reproduce this by creating a new category called "Web Dev" and it automatically changes to WebDev.

I think this category was introduced a while back before there was stricter rules on spaces in category names.

I suggest deleting that category and creating it again.

You shouldn't be able to get yourself into this situation again.

**Comment by jsolly** [comment]
Are you sure this is the first step?
> Create a category in the admin site and assign it a slug of "webdev".

If that is the case, the error shouldn't have a space in it. I think you might have two categories. One called webdev and another called Web Dev that was created a long time ago.

Please confirm for me.

**Comment by freedompraise** [comment]
> I tried to reproduce this by creating a new category called "Web Dev" and it automatically changes to WebDev.
> 
> I think this category was introduced a while back before there was stricter rules on spaces in category names.
> 
> I suggest deleting that category and creating it again.
> 
> You shouldn't be able to get yourself into this situation again.

Okay, let me delete the category

**Comment by freedompraise** [comment]
> Are you sure this is the first step?
> 
> > Create a category in the admin site and assign it a slug of "webdev".
> 
> If that is the case, the error shouldn't show a category with a space in it. I think you might have two categories. One called webdev and another called Web Dev which was created a long time ago.
> 
> Please confirm for me.

No, I only have one category called "Web Dev". It's slug is "webdev"

**Comment by freedompraise** [comment]
> 

I deleted and went over the whole process again, and I'm getting same errors

**Comment by freedompraise** [comment]
It breaks whenever I try to open the post after creation. I feel it could be from one of the templates

**Comment by jsolly** [comment]
We had a zoom call about it and weren't able to figure it out. 

I pushed some changes that will allow you to debug the application while it runs. Let me know if you can hit breakpoints and let's take it from there.

**Comment by jsolly** [comment]
Fixed in https://github.com/jsolly/blogthedata/commit/f67d639e74e4311531151612077434788e610f58

The issue was that the URLs were using the category name and using the template option `|slugify` to turn it into a 'slug'

This only worked because the categories and names I have been using were very similar.

Now we only use the slug when manufacturing URLS for blog posts or categories.

@freedompraise is this working for you now?

**Comment by freedompraise** [comment]
Yes, it works for me
