### ISSUE TITLE
Title: Error in loading database settings from environment variable

### ISSUE THREAD

**Issue by freedompraise** [jsolly/blogthedata#320]
**Description:**
I encountered an error while trying to load the database settings from the environment variable DJANGO_DB_SETTINGS in my Django project. The error message indicates a JSONDecodeError, specifically ```"Expecting value: line 4 column 17 (char 83)".```

**Steps to Reproduce:**
- Set the DJANGO_DB_SETTINGS environment variable in the ```.env``` file.
- Run the Django application.
- Observe the error message in the console.

**Expected Behavior:**
The database settings should be loaded successfully from the ```DJANGO_DB_SETTINGS``` environment variable, and the Django application should start without any errors.

**Actual Behavior:**
The Django application fails to load the database settings and raises a ```JSONDecodeError```, pointing to an issue with the content or format of the ```DB_SETTINGS_STRING```.

**Additional Information:**
I have verified the format and content of the DB_SETTINGS_STRING in my ```.env``` file, and it appears to be a valid JSON string representing the database settings.
I have also confirmed that the required environment variable ```DJANGO_DB_SETTINGS``` is properly set and accessible to the Django application.

**Comment by jsolly** [comment]
Hi @freedompraise !

I made this all a lot simpler in https://github.com/jsolly/blogthedata/pull/321 which I just merged into master.

By default, all tests are now run using sqlite instead of postgres.

If you want to use sqlite for development or production, add `USE_SQLITE=True` to your .env file.

Let me know if that works for you!

**Comment by freedompraise** [comment]
alright. Let me try it out

**Comment by freedompraise** [comment]
it works perfectly
