### ISSUE TITLE
Upgrade Django to 4.0

### ISSUE THREAD

**Issue by justin107d** [jsolly/blogthedata#37]
Django 4.0 came out this past fall and it may be nice to upgrade it to the newest version.  

[Upgrade Docs](https://docs.djangoproject.com/en/4.0/howto/upgrade-version/)
[Depreciation Timeline](https://docs.djangoproject.com/en/4.0/internals/deprecation/)

One benefit is that 4.0 implements a setting for [Cross-Origin Opener Policy](https://docs.djangoproject.com/en/4.0/ref/middleware/#cross-origin-opener-policy)

### Roadblocks
One of the modules we use, django-admin-honeypot, seems to have issues with django 4.0 ...There's a [sketchy unmerged PR](https://github.com/dmpayton/django-admin-honeypot/pull/88) about fixing errors in 4.0.

I also notice that HTMX is not supported on 4.0
https://django-htmx.readthedocs.io/en/latest/installation.html

**Comment by jsolly** [comment]
Thanks for the issue @justin107d ! I edited the issue description to add more info.

**Comment by jsolly** [comment]
Upgrade complete. Tested on https://github.com/jsolly/blogthedata/pull/105

Merging and updating production shortly

**Comment by jsolly** [comment]
Verified in production. Everything looks good!
